---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

# **Education**

## Mailman School of Public Health, Columbia University   *New York City, New York*
### Master of Public Health in Epidemiology | GPA: 4.23 | Expected Graduation May 2024

* Infectious Disease Epidemiology certificate
* Courses: Infectious Disease Epidemiology, Emerging Infectious Diseases, Spatial Epidemiology, Analysis of Categorical Data, Application of Epidemiological Research Methods, and Data Science I
* President of Students for One Health organization

## University of Virginia   *Charlottesville, Virginia*
### Bachelor of Arts in Global Public Health and Religious Studies | GPA: 3.91 | August 2015 - May 2019

* Echols Scholars Program, Dean’s List, and Intermediate Honors
* Capstone project: Human T-Cell Lymphotropic Virus Type 1 in Rural Peru
* Small Group Leader in the Women’s Leadership Development Program

# **Work Experience**

## Mailman School of Public Health, Columbia University   *New York City, New York*
### Epidemiology 1 Teaching Assistant | GPA: 3.91 | September 2023 – present

* Lead a seminar section of 25 students, reviewing course content and guiding students through practice exercises
* Maintain the course’s Canvas portal, scheduling material postings and troubleshooting technical issues

## Rakai Health Sciences Program   *Kalisizo, Uganda*
### Graduate Research Assistant | June – August 2023

* Conducted quantitative data analysis in STATA investigating associations between demographics, HIV risk
behaviors, and PrEP knowledge, use, and discontinuation among youths age 15 to 24 in south-central Uganda
* Identified relevant variables, tracked discrepancies across questionnaire versions, and created a codebook
* Collaborated with research team and site data managers to address roadblocks in data acquisition and analysis

## Epic Systems   *Verona, Wisconsin*
### Quality Manager Team Lead | June 2021 – May 2022
### Quality Manager | August 2019 – June 2021

* Tested 421 fixes and new features for Epic’s population health application, considering end-user workflows and usability heuristics to catch 193 important or critical issues
* Headed 10 software development projects, coordinating timelines, scope, and stakeholder involvement
* Managed and evaluated performance of 5 quality managers as a Team Lead
* Analyzed CDSi immunization schedule logic specifications for COVID-19 and other immunizations to identify key test cases and variations from clinical guidelines
* Crafted concise customer-facing documentation detailing new features and implementation steps

## International Rescue Committee   *Charlottesville, Virginia*
### Employment Intern | August 2018 – May 2019

* Coordinated with the casework and employment teams to establish clients in their new communities
* Acted as a liaison between clients and interpreters in financial appointments and job interviews
* Researched potential employment opportunities for International Rescue Committee clients

## Hesperian Health Guides   *Berkeley, California*
### Digital Projects Assistant | June – August 2018

* Digitized Spanish language health advocacy guides for the Hesperian HealthWiki
* Edited and proofed HealthWiki webpages and images using HTML and Wikicode