---
title: "Data Science in Action"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)

library(tidyverse)
library(p8105.datasets)
```

```{r}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX", "SNOW", "SNWD"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |> 
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin/10,
    tmax = tmax/10
  )

```

Column {data-width=650}
-----------------------------------------------------------------------

### Total Monthly Precipitation, 2022

```{r}
weather |> 
  separate(date, into = c("year", "month", "day"), sep = "-") |> 
  filter(year == "2022") |> 
  group_by(name, month) |> 
  summarize(total_precip = sum(prcp)) |> 
  mutate(
    month = case_match(month,
                     "01" ~ "Jan",
                     "02" ~ "Feb",
                     "03" ~ "Mar",
                     "04" ~ "Apr",
                     "05" ~ "May",
                     "06" ~ "Jun",
                     "07" ~ "Jul",
                     "08" ~ "Aug",
                     "09" ~ "Sep",
                     "10" ~ "Oct",
                     "11" ~ "Nov",
                     "12" ~ "Dec"),
    month = factor(month, 
                       levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), 
                       ordered = TRUE),
    text_label = str_c("Total Precipitation: ", (total_precip), " tenths of an inch")
  ) |> 
  plot_ly(
    x = ~month, y = ~total_precip, color = ~name, type = "bar", colors = "viridis", text = ~text_label) |> 
  layout(
    xaxis = list(title = "Month of 2021"), 
    yaxis = list(title = "Total Precipitation (tenths of in.)"), 
    legend  = list(title = list(text = "Location"))    
  )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Snow Depth in Waterhole WA, 2021 - 2022

```{r}
weather |> 
  filter(name == "Waterhole_WA") |> 
  mutate(
    text_label = str_c("Depth: ", snwd, " inches")
  ) |> 
  plot_ly(
    x = ~date, y = ~snwd, type = "scatter", mode = "line", 
    color = ~name, colors = "viridis", text = ~text_label, fill = "tozeroy") |>
  layout(
    xaxis = list(title = "Date"), 
    yaxis = list(title = "Snow Depth (in.)")
  )
```


### Daily Precipitation vs. Size of Temperature Range

```{r}
weather |> 
  mutate(
    trange = tmax - tmin,
    text_label = str_c("Size of temperature range: ", trange, " degrees C")
  ) |> 
  filter(prcp > 0 & prcp < 1500 & trange < 20) |> 
  plot_ly(
    x = ~trange, y = ~prcp, type = "scatter", mode = "markers", 
    color = ~name, colors = "viridis", text = ~text_label, alpha = 0.5) |>
  layout(
    xaxis = list(title = "Size of Temperature Range (degrees C)"), 
    yaxis = list(title = "Precipitation (tenths of in.)"), 
    legend  = list(title = list(text = "Location"))
  )

```
